version: latest

services:
  postgres:
    image: postgres:latest
    container_name: postgres-pro
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 3030:3030
    command: -p 3030
    volumes:
      - postgres-data-pro:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-pro
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    volumes:
      - pgadmin-data-pro:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data-pro:
  postgres-data-pro:
